language: java
os: linux
jdk: openjdk8
git:
  depth: false # https://stackoverflow.com/a/51727114/3714539
before_install:
  - source scripts/website/setup-build-tools.sh
script: scripts/travis.sh
addons:
  apt:
    update: true
stages:
  - name: test
  - name: release-snapshot
    if: (branch = master AND type = push) AND (tag IS NOT present)
  - name: release
    if: tag IS present
  - name: upload-launcher
    if: tag IS present
  - name: upload-launcher-gh-pages
    if: tag IS present
  - name: update-brew-formula
    if: tag IS present
  - name: update-versioned-docs
    if: tag IS present
  - name: update-website
    if: (branch = master AND type = push) OR (tag IS present)
  - name: upload-launchers # TODO Move a bit up once this is deemed stable enough
    if: tag IS present
  - name: upload-launchers-to-repo
    if: tag IS present
jobs:
  include:
    - env: SCALA_VERSION=2.12 BOOTSTRAP=1
      addons:
        apt:
          packages:
            - nailgun
    - env: SCALA_VERSION=2.13
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12
      sudo: required
      services: docker
      before_script: source scripts/travis-setup-graalvm.sh
    - env: SCALA_VERSION=2.12
      jdk: openjdk11
      script: sbt scala212 test:compile testsJVM/test
    - env: SCALA_VERSION=2.11
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12 NATIVE=1
      before_script: curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    - env: SCALA_VERSION=2.12 SCALA_JS=1
    - name: "Website"
      script: amm scripts/site.sc --publishLocal true
    - name: "Pants"
      before_script: pyenv global system 3.6.7
      # Sanity check for Pants build path.
      script: cd modules && ./pants run cli:coursier-cli -- fetch --help
    - stage: release-snapshot
      env: DUMMY_PROGUARD=1
      script: sbt ci-release
    - stage: release
      # publishLocal so that proguard and all compilation run before any publishing
      script: sbt +publishLocal ci-release
    - stage: upload-launcher
      env: REPO="coursier/coursier" NAME="coursier" CMD="./scripts/generate-launcher.sh -f --bat=true"
      script: scripts/upload-launcher/upload-gh-release.sh
    - stage: upload-launcher-gh-pages
      env: REPO="coursier/coursier" NAME="coursier"
      script: scripts/upload-launcher/upload-gh-pages.sh
    - stage: update-brew-formula
      env: REPO="coursier/coursier" FORMULA_REPO="coursier/homebrew-formulas" NAME=coursier TEMPLATE=scripts/coursier.rb.template
      script: scripts/upload-launcher/update-brew-formula.sh
    - stage: update-versioned-docs
      env: WEBSITE_DIR=doc/website VERSIONED_DOCS_REPO=coursier/versioned-docs
      script:
        - amm scripts/site.sc --publishLocal true --npmInstall true --yarnRunBuild true
        - scripts/website/versioned-docs.sh --update
    - stage: update-website
      env: WEBSITE_DIR=doc/website REPO=coursier/coursier VERSIONED_DOCS_REPO=coursier/versioned-docs
      name: "Push website"
      script:
        - npm install
        - export PATH="$PATH:$(pwd)/node_modules/bower/bin"
        - scripts/website/versioned-docs.sh
        - amm scripts/site.sc --publishLocal true --npmInstall true --yarnRunBuild true --relativize true
        - scripts/copy-demo.sh
        - scripts/website/push-website.sh
    - stage: upload-launchers
      name: "Push assembly"
      script: scripts/travis-assembly.sh
    - stage: upload-launchers
      name: "Push Linux graalvm launcher"
      env: LAUNCHER_OS=x86_64-pc-linux
      script: scripts/travis-native-image.sh
    - stage: upload-launchers
      name: "Push OS X graalvm launcher"
      env: LAUNCHER_OS=x86_64-apple-darwin # vaguely like llvm target triple
      os: osx
      osx_image: xcode9.4
      jdk: openjdk9
      before_install:
        - brew install jq
      script: scripts/travis-native-image.sh
    - stage: upload-launchers
      name: "Push Windows jlink launcher"
      env: LAUNCHER_OS=x86_64-pc-win32
      os: windows
      language: bash
      script: scripts/travis-jlink.sh
    - stage: upload-launchers-to-repo
      env: LAUNCHER_REPO="coursier/launchers" LAUNCHER_BRANCH="master" REPO="coursier/coursier" NAME="coursier coursier.asc coursier.bat coursier.bat.asc coursier.jar coursier.jar.asc cs-x86_64-apple-darwin cs-x86_64-apple-darwin.asc cs-x86_64-pc-linux cs-x86_64-pc-linux.asc standalone-x86_64-pc-win32.zip standalone-x86_64-pc-win32.zip.asc" # TODO Get those via the GitHub API?
      script: scripts/upload-launcher/upload-gh-pages.sh
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
  - $HOME/.jabba/jdk
