language: java
os: linux
dist: xenial
jdk: openjdk8
git:
  depth: false # https://stackoverflow.com/a/51727114/3714539

before_install:
  - source scripts/ci-setup.sh
script: scripts/ci.sh

addons:
  apt:
    update: true
    packages:
      - nailgun

stages:
  - name: test
  - name: release-snapshot
    if: (branch = master AND type = push) AND (tag IS NOT present)
  - name: release
    if: tag IS present
  - name: upload-jar-launchers
    if: tag IS present
  - name: upload-native-launchers
    if: tag IS present
  - name: update-brew-formula
    if: tag IS present
  - name: update-website
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - env: SCALA_VERSION=2.13
      services: docker
    - env: SCALA_VERSION=2.12
      services: docker
    - env: SCALA_VERSION=2.12
      jdk: openjdk11
    - env: TARGET=ScalaNative
    - env: TARGET=Scala.JS
    - name: "Website"
      env: TARGET=Website

    - stage: release-snapshot
      script: sbt ci-release
    - stage: release
      # publishLocal so that proguard and all compilation run before any publishing
      script: sbt +publishLocal ci-release

    - stage: upload-jar-launchers
      script: amm launcher.sc uploadAllJars
    - stage: upload-native-launchers
      name: "Push Linux native image"
      before_script: source scripts/shared/setup-graalvm.sh
      script: amm launcher.sc uploadNativeImage
    - stage: upload-native-launchers
      name: "Push mac native image"
      os: osx
      osx_image: xcode9.4
      jdk: openjdk9
      before_script: source scripts/shared/setup-graalvm.sh
      script: amm launcher.sc uploadNativeImage
    - stage: upload-native-launchers
      name: "Push Windows native image"
      os: windows
      language: bash
      before_script: source scripts/shared/setup-graalvm.sh
      script: gpg --version && amm.bat launcher.sc signDummyFiles && scripts/windows-native-image.bat && gpgconf --kill gpg-agent
    - stage: update-brew-formula
      script: scripts/update-brew-formula.sh
    - stage: update-website
      name: "Push website"
      script:
        - npm install
        - export PATH="$PATH:$(pwd)/node_modules/bower/bin"
        - amm website.sc updateWebsite
# Only build if: master branch, a tag, or a fork
if: branch = master
    OR tag IS present
    OR repo != coursier/coursier
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
  - $HOME/.jabba/jdk
