language: java
os: linux
jdk: oraclejdk8
script: scripts/travis.sh
addons:
  apt:
    update: true
stages:
  - name: test
  - name: upload-launcher
    if: tag IS present
  - name: update-website
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - env: SCALA_VERSION=2.13
      before_install: ./scripts/setup-build-tools.sh
      script: bin/sbt scala213 testsJVM/test
    - env: SCALA_VERSION=2.12 NATIVE=1
      sudo: required
      before_install: curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      services: docker
    - env: SCALA_VERSION=2.12
      jdk: openjdk11
      before_install: ./scripts/setup-build-tools.sh
      script: bin/sbt scala212 test:compile testsJVM/test
    - env: SCALA_VERSION=2.11
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12 SCALA_JS=1
    - env: SCALA_VERSION=2.11 SCALA_JS=1
    - env: PANTS=1 # unused in the script, just to tag the job on the Travis CI UI
      # Sanity check for Pants build path.
      script: cd modules && ./pants run cli/src/main/scala-2.12:coursier-cli -- fetch --help
    - env: WEBSITE=1 # unused from the script, just to know what the job does from the Travis UI
      script: scripts/update-website.sh
    - stage: upload-launcher
      env: UPLOAD_LAUNCHER=1 # unused from the script, just to know what the job does from the Travis UI
      script: scripts/upload-launcher.sh
    - stage: update-website
      env: PUSH_WEBSITE=1
      script: scripts/update-website.sh
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
