# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xmx4g -Xss2m
environment:
  TEST_REPOSITORY_HOST: localhost
  TEST_REPOSITORY_PORT: 8080
  TEST_REPOSITORY_USER: user
  TEST_REPOSITORY_PASSWORD: pass
  TEST_REPOSITORY: http://localhost:8080
  TEST_REDIRECT_REPOSITORY: disabled
build_script:
  - sbt cli/pack
  - cmd: .\modules\cli\target\pack\bin\coursier bootstrap io.get-coursier:echo:1.0.1 -o cs-echo
  - cmd: .\cs-echo foo
  - sbt testsJVM/test:compile # this checks out some git submodules
  - ps: Start-Job -filepath .\modules\tests\handmade-metadata\scripts\start-it-auth-server.ps1 -ArgumentList $pwd\modules\tests\handmade-metadata, $env:TEST_REPOSITORY_HOST, $env:TEST_REPOSITORY_PORT, $env:TEST_REPOSITORY_USER, $env:TEST_REPOSITORY_PASSWORD
  - sbt scala212 coreJVM/publishLocal cacheJVM/publishLocal extra/publishLocal scalazJVM/publishLocal cli/publishLocal
  - sbt scala211 compile coreJVM/publishLocal
test_script:
  - sbt scala213 testsJVM/test
  - sbt scala212 testsJVM/test
  - sbt scala211 testsJVM/test
  - sbt scala213 testsJVM/it:test
  - sbt scala212 testsJVM/it:test
  - sbt scala211 testsJVM/it:test
branches:
  only:
    - master
